### ISSUE TITLE
LifterLMS Labs(Action Manager) don't work anymore

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms-labs#15]
Action Manager in LifterLMS Labs does not hide the elements on the course page anymore.

HS-122914

**Comment by thomasplevy** [comment]
This is expected behavior when using the block editor.

If you wish to remove blocks, delete them via the block editor.

The action manager was designed to manage elements that were not manageable via a user interface in the days prior to the block editor.

It DOES NOT manage blocks!
