### ISSUE TITLE
PHP8 and WP5.6 Compat

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-labs#17]
Add-on Checklist

+ Composer Updates
	+ lifterlms/lifterlms-tests
		+ [ ] Switch from "dev-master" to "dev-trunk"
		+ [ ] Update to latest version
	+ lifterlms/lifterlms-cs
		+ [ ] Switch from "dev-master" to "dev-trunk"
		+ [ ] Update to latest version
	+ Scripts
		+ [ ] Update scripts to match the LifterLMS Core scripts block
		+ [ ] Ensure any custom scripts are retained
		+ [ ] Ensure database scripts use a custom default database name, eg "llms_groups_tests" instead of "llms_tests"
		+ [ ] If the add-on is not configured for E2E testing the "env" and "env:setup" commands can be removed
	+ PHP Requirements
		+ [ ] Update PHP version to be >=7.2

+ Travis Config Updates
	+ [ ] Update to import the add-on.yml config from the LLMS core.
	+ [ ] Import the e2e config if the add-on is setup for e2e testing
	+ [ ] Retain any custom jobs specific to the add-on

+ Tests
	+ [ ] Test Suite Passes in Travis
	+ [x] Passes manual inspection on php8

**Comment by eri-trabiccolo** [comment]
This looks fine on a manual inspection.
On the other hand this add-on doesn't have:

- travis configuration
- tests and tests configuration
- cs configuration

So I didn't update the composer.json
I'm closing this.
